2021-05-25 19:44:07,526 ERROR: Exception on /api/runs/1/141 [GET] [in /Users/inuur/Desktop/Git Projects/uvo-reserves-demo/venv/lib/python3.9/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/Users/inuur/Desktop/Git Projects/uvo-reserves-demo/venv/lib/python3.9/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/inuur/Desktop/Git Projects/uvo-reserves-demo/venv/lib/python3.9/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/inuur/Desktop/Git Projects/uvo-reserves-demo/venv/lib/python3.9/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/Users/inuur/Desktop/Git Projects/uvo-reserves-demo/venv/lib/python3.9/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/inuur/Desktop/Git Projects/uvo-reserves-demo/venv/lib/python3.9/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/inuur/Desktop/Git Projects/uvo-reserves-demo/venv/lib/python3.9/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/inuur/Desktop/Git Projects/uvo-reserves-demo/venv/lib/python3.9/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/inuur/Desktop/Git Projects/uvo-reserves-demo/venv/lib/python3.9/site-packages/flask_jwt_extended/view_decorators.py", line 121, in decorator
    return fn(*args, **kwargs)
TypeError: decorated_function() got an unexpected keyword argument 'well_id'
2021-05-25 19:45:31,774 INFO: uvo-reserves [in /Users/inuur/Desktop/Git Projects/uvo-reserves-demo/app/__init__.py:80]
2021-05-25 19:45:31,774 INFO: uvo-reserves startup [in /Users/inuur/Desktop/Git Projects/uvo-reserves-demo/app/__init__.py:101]
2021-05-25 19:45:31,774 INFO: uvo-reserves startup [in /Users/inuur/Desktop/Git Projects/uvo-reserves-demo/app/__init__.py:101]
2021-05-25 19:45:36,420 ERROR: Exception on /api/runs/1/141 [GET] [in /Users/inuur/Desktop/Git Projects/uvo-reserves-demo/venv/lib/python3.9/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/Users/inuur/Desktop/Git Projects/uvo-reserves-demo/venv/lib/python3.9/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/inuur/Desktop/Git Projects/uvo-reserves-demo/venv/lib/python3.9/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/inuur/Desktop/Git Projects/uvo-reserves-demo/venv/lib/python3.9/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/Users/inuur/Desktop/Git Projects/uvo-reserves-demo/venv/lib/python3.9/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/inuur/Desktop/Git Projects/uvo-reserves-demo/venv/lib/python3.9/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/inuur/Desktop/Git Projects/uvo-reserves-demo/venv/lib/python3.9/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/inuur/Desktop/Git Projects/uvo-reserves-demo/venv/lib/python3.9/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/inuur/Desktop/Git Projects/uvo-reserves-demo/venv/lib/python3.9/site-packages/flask_jwt_extended/view_decorators.py", line 121, in decorator
    return fn(*args, **kwargs)
  File "/Users/inuur/Desktop/Git Projects/uvo-reserves-demo/app/api/crvs.py", line 16, in core_view
    return jsonify({'well': well.name,
AttributeError: 'NoneType' object has no attribute 'name'
2021-05-25 19:45:36,420 ERROR: Exception on /api/runs/1/141 [GET] [in /Users/inuur/Desktop/Git Projects/uvo-reserves-demo/venv/lib/python3.9/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/Users/inuur/Desktop/Git Projects/uvo-reserves-demo/venv/lib/python3.9/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/inuur/Desktop/Git Projects/uvo-reserves-demo/venv/lib/python3.9/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/inuur/Desktop/Git Projects/uvo-reserves-demo/venv/lib/python3.9/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/Users/inuur/Desktop/Git Projects/uvo-reserves-demo/venv/lib/python3.9/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/inuur/Desktop/Git Projects/uvo-reserves-demo/venv/lib/python3.9/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/inuur/Desktop/Git Projects/uvo-reserves-demo/venv/lib/python3.9/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/inuur/Desktop/Git Projects/uvo-reserves-demo/venv/lib/python3.9/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/inuur/Desktop/Git Projects/uvo-reserves-demo/venv/lib/python3.9/site-packages/flask_jwt_extended/view_decorators.py", line 121, in decorator
    return fn(*args, **kwargs)
  File "/Users/inuur/Desktop/Git Projects/uvo-reserves-demo/app/api/crvs.py", line 16, in core_view
    return jsonify({'well': well.name,
AttributeError: 'NoneType' object has no attribute 'name'
2021-05-25 19:46:54,348 ERROR: Exception on /api/runs/1/141 [GET] [in /Users/inuur/Desktop/Git Projects/uvo-reserves-demo/venv/lib/python3.9/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/Users/inuur/Desktop/Git Projects/uvo-reserves-demo/venv/lib/python3.9/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/inuur/Desktop/Git Projects/uvo-reserves-demo/venv/lib/python3.9/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/inuur/Desktop/Git Projects/uvo-reserves-demo/venv/lib/python3.9/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/Users/inuur/Desktop/Git Projects/uvo-reserves-demo/venv/lib/python3.9/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/inuur/Desktop/Git Projects/uvo-reserves-demo/venv/lib/python3.9/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/inuur/Desktop/Git Projects/uvo-reserves-demo/venv/lib/python3.9/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/inuur/Desktop/Git Projects/uvo-reserves-demo/venv/lib/python3.9/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/inuur/Desktop/Git Projects/uvo-reserves-demo/venv/lib/python3.9/site-packages/flask_jwt_extended/view_decorators.py", line 121, in decorator
    return fn(*args, **kwargs)
  File "/Users/inuur/Desktop/Git Projects/uvo-reserves-demo/app/api/crvs.py", line 16, in core_view
    return jsonify({'well': well.name,
AttributeError: 'NoneType' object has no attribute 'name'
2021-05-25 19:46:54,348 ERROR: Exception on /api/runs/1/141 [GET] [in /Users/inuur/Desktop/Git Projects/uvo-reserves-demo/venv/lib/python3.9/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/Users/inuur/Desktop/Git Projects/uvo-reserves-demo/venv/lib/python3.9/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/inuur/Desktop/Git Projects/uvo-reserves-demo/venv/lib/python3.9/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/inuur/Desktop/Git Projects/uvo-reserves-demo/venv/lib/python3.9/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/Users/inuur/Desktop/Git Projects/uvo-reserves-demo/venv/lib/python3.9/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/inuur/Desktop/Git Projects/uvo-reserves-demo/venv/lib/python3.9/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/inuur/Desktop/Git Projects/uvo-reserves-demo/venv/lib/python3.9/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/inuur/Desktop/Git Projects/uvo-reserves-demo/venv/lib/python3.9/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/inuur/Desktop/Git Projects/uvo-reserves-demo/venv/lib/python3.9/site-packages/flask_jwt_extended/view_decorators.py", line 121, in decorator
    return fn(*args, **kwargs)
  File "/Users/inuur/Desktop/Git Projects/uvo-reserves-demo/app/api/crvs.py", line 16, in core_view
    return jsonify({'well': well.name,
AttributeError: 'NoneType' object has no attribute 'name'
2021-05-25 19:47:07,066 INFO: uvo-reserves [in /Users/inuur/Desktop/Git Projects/uvo-reserves-demo/app/__init__.py:80]
2021-05-25 19:47:07,067 INFO: uvo-reserves startup [in /Users/inuur/Desktop/Git Projects/uvo-reserves-demo/app/__init__.py:101]
2021-05-25 19:47:07,067 INFO: uvo-reserves startup [in /Users/inuur/Desktop/Git Projects/uvo-reserves-demo/app/__init__.py:101]
