2021-04-06 14:15:13,350 INFO: uvo-reserves [in /home/sumbel/PycharmProjects/uvo-reserves-demo/app/__init__.py:74]
2021-04-06 16:46:42,061 INFO: uvo-reserves [in /home/sumbel/PycharmProjects/uvo-reserves-demo/app/__init__.py:74]
2021-04-06 16:46:44,769 ERROR: Exception on /las_uploader [POST] [in /home/sumbel/PycharmProjects/uvo-reserves-demo/venv/lib/python3.6/site-packages/flask/app.py:1892]
Traceback (most recent call last):
  File "/home/sumbel/PycharmProjects/uvo-reserves-demo/venv/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/sumbel/PycharmProjects/uvo-reserves-demo/venv/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/sumbel/PycharmProjects/uvo-reserves-demo/venv/lib/python3.6/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/sumbel/PycharmProjects/uvo-reserves-demo/venv/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/sumbel/PycharmProjects/uvo-reserves-demo/venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/sumbel/PycharmProjects/uvo-reserves-demo/venv/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/sumbel/PycharmProjects/uvo-reserves-demo/venv/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/sumbel/PycharmProjects/uvo-reserves-demo/app/main/routes.py", line 124, in las_uploader
    well_info = read_lasio(os.path.join(current_app.config['UPLOAD_FOLDER'], filename))
  File "/home/sumbel/PycharmProjects/uvo-reserves-demo/app/helpers/parser.py", line 34, in read_lasio
    W_i = lasio.read(path_lasio, encoding=enc)
  File "/home/sumbel/PycharmProjects/uvo-reserves-demo/venv/lib/python3.6/site-packages/lasio/__init__.py", line 45, in read
    return LASFile(file_ref, **kwargs)
  File "/home/sumbel/PycharmProjects/uvo-reserves-demo/venv/lib/python3.6/site-packages/lasio/las.py", line 81, in __init__
    self.read(file_ref, **read_kwargs)
  File "/home/sumbel/PycharmProjects/uvo-reserves-demo/venv/lib/python3.6/site-packages/lasio/las.py", line 149, in read
    raise KeyError("No ~ sections found. Is this a LAS file?")
KeyError: 'No ~ sections found. Is this a LAS file?'
2021-04-06 16:46:46,886 ERROR: Exception on /las_uploader [POST] [in /home/sumbel/PycharmProjects/uvo-reserves-demo/venv/lib/python3.6/site-packages/flask/app.py:1892]
Traceback (most recent call last):
  File "/home/sumbel/PycharmProjects/uvo-reserves-demo/venv/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/sumbel/PycharmProjects/uvo-reserves-demo/venv/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/sumbel/PycharmProjects/uvo-reserves-demo/venv/lib/python3.6/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/sumbel/PycharmProjects/uvo-reserves-demo/venv/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/sumbel/PycharmProjects/uvo-reserves-demo/venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/sumbel/PycharmProjects/uvo-reserves-demo/venv/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/sumbel/PycharmProjects/uvo-reserves-demo/venv/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/sumbel/PycharmProjects/uvo-reserves-demo/app/main/routes.py", line 124, in las_uploader
    well_info = read_lasio(os.path.join(current_app.config['UPLOAD_FOLDER'], filename))
  File "/home/sumbel/PycharmProjects/uvo-reserves-demo/app/helpers/parser.py", line 34, in read_lasio
    W_i = lasio.read(path_lasio, encoding=enc)
  File "/home/sumbel/PycharmProjects/uvo-reserves-demo/venv/lib/python3.6/site-packages/lasio/__init__.py", line 45, in read
    return LASFile(file_ref, **kwargs)
  File "/home/sumbel/PycharmProjects/uvo-reserves-demo/venv/lib/python3.6/site-packages/lasio/las.py", line 81, in __init__
    self.read(file_ref, **read_kwargs)
  File "/home/sumbel/PycharmProjects/uvo-reserves-demo/venv/lib/python3.6/site-packages/lasio/las.py", line 149, in read
    raise KeyError("No ~ sections found. Is this a LAS file?")
KeyError: 'No ~ sections found. Is this a LAS file?'
2021-04-06 16:46:47,555 ERROR: Exception on /las_uploader [POST] [in /home/sumbel/PycharmProjects/uvo-reserves-demo/venv/lib/python3.6/site-packages/flask/app.py:1892]
Traceback (most recent call last):
  File "/home/sumbel/PycharmProjects/uvo-reserves-demo/venv/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/sumbel/PycharmProjects/uvo-reserves-demo/venv/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/sumbel/PycharmProjects/uvo-reserves-demo/venv/lib/python3.6/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/sumbel/PycharmProjects/uvo-reserves-demo/venv/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/sumbel/PycharmProjects/uvo-reserves-demo/venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/sumbel/PycharmProjects/uvo-reserves-demo/venv/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/sumbel/PycharmProjects/uvo-reserves-demo/venv/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/sumbel/PycharmProjects/uvo-reserves-demo/app/main/routes.py", line 124, in las_uploader
    well_info = read_lasio(os.path.join(current_app.config['UPLOAD_FOLDER'], filename))
  File "/home/sumbel/PycharmProjects/uvo-reserves-demo/app/helpers/parser.py", line 34, in read_lasio
    W_i = lasio.read(path_lasio, encoding=enc)
  File "/home/sumbel/PycharmProjects/uvo-reserves-demo/venv/lib/python3.6/site-packages/lasio/__init__.py", line 45, in read
    return LASFile(file_ref, **kwargs)
  File "/home/sumbel/PycharmProjects/uvo-reserves-demo/venv/lib/python3.6/site-packages/lasio/las.py", line 81, in __init__
    self.read(file_ref, **read_kwargs)
  File "/home/sumbel/PycharmProjects/uvo-reserves-demo/venv/lib/python3.6/site-packages/lasio/las.py", line 149, in read
    raise KeyError("No ~ sections found. Is this a LAS file?")
KeyError: 'No ~ sections found. Is this a LAS file?'
2021-04-06 17:09:00,977 INFO: uvo-reserves [in /home/sumbel/PycharmProjects/uvo-reserves-demo/app/__init__.py:75]
2021-04-06 17:09:35,341 INFO: uvo-reserves [in /home/sumbel/PycharmProjects/uvo-reserves-demo/app/__init__.py:75]
2021-04-07 08:55:17,004 INFO: uvo-reserves [in /home/sumbel/PycharmProjects/uvo-reserves-demo/app/__init__.py:75]
2021-04-07 12:22:09,864 INFO: uvo-reserves [in /home/sumbel/PycharmProjects/uvo-reserves-demo/app/__init__.py:75]
2021-04-07 12:22:09,865 INFO: uvo-reserves startup [in /home/sumbel/PycharmProjects/uvo-reserves-demo/app/__init__.py:96]
2021-04-07 12:22:09,865 INFO: uvo-reserves startup [in /home/sumbel/PycharmProjects/uvo-reserves-demo/app/__init__.py:96]
2021-04-10 13:14:45,109 INFO: uvo-reserves [in /home/sumbel/PycharmProjects/uvo-reserves-demo/app/__init__.py:75]
2021-04-10 13:14:45,110 INFO: uvo-reserves startup [in /home/sumbel/PycharmProjects/uvo-reserves-demo/app/__init__.py:96]
2021-04-10 13:14:45,110 INFO: uvo-reserves startup [in /home/sumbel/PycharmProjects/uvo-reserves-demo/app/__init__.py:96]
2021-04-27 19:57:46,530 INFO: uvo-reserves [in /home/sumbel/PycharmProjects/uvo-reserves-demo/app/__init__.py:75]
2021-04-27 19:57:46,531 INFO: uvo-reserves startup [in /home/sumbel/PycharmProjects/uvo-reserves-demo/app/__init__.py:96]
2021-04-27 19:57:46,531 INFO: uvo-reserves startup [in /home/sumbel/PycharmProjects/uvo-reserves-demo/app/__init__.py:96]
2021-05-03 13:14:28,823 INFO: uvo-reserves [in /home/sumbel/PycharmProjects/uvo-reserves-demo/app/__init__.py:77]
2021-05-03 13:14:28,824 INFO: uvo-reserves startup [in /home/sumbel/PycharmProjects/uvo-reserves-demo/app/__init__.py:98]
2021-05-03 13:14:28,824 INFO: uvo-reserves startup [in /home/sumbel/PycharmProjects/uvo-reserves-demo/app/__init__.py:98]
2021-05-03 13:17:58,621 INFO: uvo-reserves [in /home/sumbel/PycharmProjects/uvo-reserves-demo/app/__init__.py:77]
2021-05-03 13:17:58,621 INFO: uvo-reserves startup [in /home/sumbel/PycharmProjects/uvo-reserves-demo/app/__init__.py:98]
2021-05-03 13:17:58,621 INFO: uvo-reserves startup [in /home/sumbel/PycharmProjects/uvo-reserves-demo/app/__init__.py:98]
2021-05-03 13:28:49,646 INFO: uvo-reserves [in /home/sumbel/PycharmProjects/uvo-reserves-demo/app/__init__.py:77]
2021-05-03 13:28:52,301 INFO: uvo-reserves startup [in /home/sumbel/PycharmProjects/uvo-reserves-demo/app/__init__.py:98]
2021-05-03 13:28:52,301 INFO: uvo-reserves startup [in /home/sumbel/PycharmProjects/uvo-reserves-demo/app/__init__.py:98]
2021-05-03 13:37:02,026 INFO: uvo-reserves [in /home/sumbel/PycharmProjects/uvo-reserves-demo/app/__init__.py:77]
2021-05-03 13:37:02,026 INFO: uvo-reserves startup [in /home/sumbel/PycharmProjects/uvo-reserves-demo/app/__init__.py:98]
2021-05-03 13:37:02,026 INFO: uvo-reserves startup [in /home/sumbel/PycharmProjects/uvo-reserves-demo/app/__init__.py:98]
