2021-05-25 19:08:20,286 ERROR: Exception on /api/runs/1 [GET] [in /Users/inuur/Desktop/Git Projects/uvo-reserves-demo/venv/lib/python3.9/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/Users/inuur/Desktop/Git Projects/uvo-reserves-demo/venv/lib/python3.9/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/inuur/Desktop/Git Projects/uvo-reserves-demo/venv/lib/python3.9/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/inuur/Desktop/Git Projects/uvo-reserves-demo/venv/lib/python3.9/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/Users/inuur/Desktop/Git Projects/uvo-reserves-demo/venv/lib/python3.9/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/inuur/Desktop/Git Projects/uvo-reserves-demo/venv/lib/python3.9/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/inuur/Desktop/Git Projects/uvo-reserves-demo/venv/lib/python3.9/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/inuur/Desktop/Git Projects/uvo-reserves-demo/venv/lib/python3.9/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/inuur/Desktop/Git Projects/uvo-reserves-demo/venv/lib/python3.9/site-packages/flask_jwt_extended/view_decorators.py", line 121, in decorator
    return fn(*args, **kwargs)
  File "/Users/inuur/Desktop/Git Projects/uvo-reserves-demo/app/api/run.py", line 73, in run_view
    return jsonify(data)
  File "/Users/inuur/Desktop/Git Projects/uvo-reserves-demo/venv/lib/python3.9/site-packages/flask/json/__init__.py", line 370, in jsonify
    dumps(data, indent=indent, separators=separators) + "\n",
  File "/Users/inuur/Desktop/Git Projects/uvo-reserves-demo/venv/lib/python3.9/site-packages/flask/json/__init__.py", line 211, in dumps
    rv = _json.dumps(obj, **kwargs)
  File "/Users/inuur/Desktop/Git Projects/uvo-reserves-demo/venv/lib/python3.9/site-packages/simplejson/__init__.py", line 398, in dumps
    return cls(
  File "/Users/inuur/Desktop/Git Projects/uvo-reserves-demo/venv/lib/python3.9/site-packages/simplejson/encoder.py", line 296, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/Users/inuur/Desktop/Git Projects/uvo-reserves-demo/venv/lib/python3.9/site-packages/simplejson/encoder.py", line 378, in iterencode
    return _iterencode(o, 0)
  File "/Users/inuur/Desktop/Git Projects/uvo-reserves-demo/venv/lib/python3.9/site-packages/flask/json/__init__.py", line 100, in default
    return _json.JSONEncoder.default(self, o)
  File "/Users/inuur/Desktop/Git Projects/uvo-reserves-demo/venv/lib/python3.9/site-packages/simplejson/encoder.py", line 272, in default
    raise TypeError('Object of type %s is not JSON serializable' %
TypeError: Object of type CoreResults is not JSON serializable
