2021-05-18 18:38:25,519 ERROR: Exception on /api/5/runs [GET] [in c:\users\lolip\desktop\git projects\uvo-reserves-demo\venv\lib\site-packages\flask\app.py:1892]
Traceback (most recent call last):
  File "c:\users\lolip\desktop\git projects\uvo-reserves-demo\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\lolip\desktop\git projects\uvo-reserves-demo\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\lolip\desktop\git projects\uvo-reserves-demo\venv\lib\site-packages\flask_cors\extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "c:\users\lolip\desktop\git projects\uvo-reserves-demo\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\lolip\desktop\git projects\uvo-reserves-demo\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\lolip\desktop\git projects\uvo-reserves-demo\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\lolip\desktop\git projects\uvo-reserves-demo\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\lolip\desktop\git projects\uvo-reserves-demo\venv\lib\site-packages\flask_jwt_extended\view_decorators.py", line 121, in decorator
    return fn(*args, **kwargs)
  File "C:\Users\lolip\Desktop\Git projects\uvo-reserves-demo\app\api\run.py", line 18, in get_runs
    'runs': [run.serialize() for run in project_runs]
  File "C:\Users\lolip\Desktop\Git projects\uvo-reserves-demo\app\api\run.py", line 18, in <listcomp>
    'runs': [run.serialize() for run in project_runs]
TypeError: 'dict' object is not callable
2021-05-18 18:39:07,673 INFO: uvo-reserves [in C:\Users\lolip\Desktop\Git projects\uvo-reserves-demo\app\__init__.py:80]
2021-05-18 18:39:07,674 INFO: uvo-reserves startup [in C:\Users\lolip\Desktop\Git projects\uvo-reserves-demo\app\__init__.py:101]
2021-05-18 18:39:07,674 INFO: uvo-reserves startup [in C:\Users\lolip\Desktop\Git projects\uvo-reserves-demo\app\__init__.py:101]
2021-05-18 18:39:13,656 INFO: uvo-reserves [in C:\Users\lolip\Desktop\Git projects\uvo-reserves-demo\app\__init__.py:80]
2021-05-18 18:39:13,657 INFO: uvo-reserves startup [in C:\Users\lolip\Desktop\Git projects\uvo-reserves-demo\app\__init__.py:101]
2021-05-18 18:39:13,657 INFO: uvo-reserves startup [in C:\Users\lolip\Desktop\Git projects\uvo-reserves-demo\app\__init__.py:101]
2021-05-18 18:39:15,193 ERROR: Exception on /api/5/runs [GET] [in c:\users\lolip\desktop\git projects\uvo-reserves-demo\venv\lib\site-packages\flask\app.py:1892]
Traceback (most recent call last):
  File "c:\users\lolip\desktop\git projects\uvo-reserves-demo\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\lolip\desktop\git projects\uvo-reserves-demo\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\lolip\desktop\git projects\uvo-reserves-demo\venv\lib\site-packages\flask_cors\extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "c:\users\lolip\desktop\git projects\uvo-reserves-demo\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\lolip\desktop\git projects\uvo-reserves-demo\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\lolip\desktop\git projects\uvo-reserves-demo\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\lolip\desktop\git projects\uvo-reserves-demo\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\lolip\desktop\git projects\uvo-reserves-demo\venv\lib\site-packages\flask_jwt_extended\view_decorators.py", line 121, in decorator
    return fn(*args, **kwargs)
  File "C:\Users\lolip\Desktop\Git projects\uvo-reserves-demo\app\api\run.py", line 17, in get_runs
    'runs': jsonify(project_runs)
  File "c:\users\lolip\desktop\git projects\uvo-reserves-demo\venv\lib\site-packages\flask\json\__init__.py", line 370, in jsonify
    dumps(data, indent=indent, separators=separators) + "\n",
  File "c:\users\lolip\desktop\git projects\uvo-reserves-demo\venv\lib\site-packages\flask\json\__init__.py", line 211, in dumps
    rv = _json.dumps(obj, **kwargs)
  File "c:\users\lolip\appdata\local\programs\python\python36\lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "c:\users\lolip\appdata\local\programs\python\python36\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "c:\users\lolip\appdata\local\programs\python\python36\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "c:\users\lolip\desktop\git projects\uvo-reserves-demo\venv\lib\site-packages\flask\json\__init__.py", line 100, in default
    return _json.JSONEncoder.default(self, o)
  File "c:\users\lolip\appdata\local\programs\python\python36\lib\json\encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'Run' is not JSON serializable
2021-05-18 18:39:15,193 ERROR: Exception on /api/5/runs [GET] [in c:\users\lolip\desktop\git projects\uvo-reserves-demo\venv\lib\site-packages\flask\app.py:1892]
Traceback (most recent call last):
  File "c:\users\lolip\desktop\git projects\uvo-reserves-demo\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\lolip\desktop\git projects\uvo-reserves-demo\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\lolip\desktop\git projects\uvo-reserves-demo\venv\lib\site-packages\flask_cors\extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "c:\users\lolip\desktop\git projects\uvo-reserves-demo\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\lolip\desktop\git projects\uvo-reserves-demo\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\lolip\desktop\git projects\uvo-reserves-demo\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\lolip\desktop\git projects\uvo-reserves-demo\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\lolip\desktop\git projects\uvo-reserves-demo\venv\lib\site-packages\flask_jwt_extended\view_decorators.py", line 121, in decorator
    return fn(*args, **kwargs)
  File "C:\Users\lolip\Desktop\Git projects\uvo-reserves-demo\app\api\run.py", line 17, in get_runs
    'runs': jsonify(project_runs)
  File "c:\users\lolip\desktop\git projects\uvo-reserves-demo\venv\lib\site-packages\flask\json\__init__.py", line 370, in jsonify
    dumps(data, indent=indent, separators=separators) + "\n",
  File "c:\users\lolip\desktop\git projects\uvo-reserves-demo\venv\lib\site-packages\flask\json\__init__.py", line 211, in dumps
    rv = _json.dumps(obj, **kwargs)
  File "c:\users\lolip\appdata\local\programs\python\python36\lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "c:\users\lolip\appdata\local\programs\python\python36\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "c:\users\lolip\appdata\local\programs\python\python36\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "c:\users\lolip\desktop\git projects\uvo-reserves-demo\venv\lib\site-packages\flask\json\__init__.py", line 100, in default
    return _json.JSONEncoder.default(self, o)
  File "c:\users\lolip\appdata\local\programs\python\python36\lib\json\encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'Run' is not JSON serializable
2021-05-18 18:39:34,516 INFO: uvo-reserves [in C:\Users\lolip\Desktop\Git projects\uvo-reserves-demo\app\__init__.py:80]
2021-05-18 18:39:34,517 INFO: uvo-reserves startup [in C:\Users\lolip\Desktop\Git projects\uvo-reserves-demo\app\__init__.py:101]
2021-05-18 18:39:34,517 INFO: uvo-reserves startup [in C:\Users\lolip\Desktop\Git projects\uvo-reserves-demo\app\__init__.py:101]
2021-05-18 18:42:22,703 INFO: uvo-reserves [in C:\Users\lolip\Desktop\Git projects\uvo-reserves-demo\app\__init__.py:80]
2021-05-18 18:42:22,704 INFO: uvo-reserves startup [in C:\Users\lolip\Desktop\Git projects\uvo-reserves-demo\app\__init__.py:101]
2021-05-18 18:42:22,704 INFO: uvo-reserves startup [in C:\Users\lolip\Desktop\Git projects\uvo-reserves-demo\app\__init__.py:101]
2021-05-18 20:40:56,930 INFO: uvo-reserves [in C:\Users\lolip\Desktop\Git projects\uvo-reserves-demo\app\__init__.py:80]
2021-05-18 20:40:56,930 INFO: uvo-reserves startup [in C:\Users\lolip\Desktop\Git projects\uvo-reserves-demo\app\__init__.py:101]
2021-05-18 20:40:56,930 INFO: uvo-reserves startup [in C:\Users\lolip\Desktop\Git projects\uvo-reserves-demo\app\__init__.py:101]
2021-05-18 20:41:19,905 INFO: uvo-reserves [in C:\Users\lolip\Desktop\Git projects\uvo-reserves-demo\app\__init__.py:80]
2021-05-18 20:41:19,906 INFO: uvo-reserves startup [in C:\Users\lolip\Desktop\Git projects\uvo-reserves-demo\app\__init__.py:101]
2021-05-18 20:41:19,906 INFO: uvo-reserves startup [in C:\Users\lolip\Desktop\Git projects\uvo-reserves-demo\app\__init__.py:101]
