2021-05-18 12:35:51,253 ERROR: Exception on /api/undefined/run [POST] [in c:\users\lolip\appdata\local\programs\python\python36\lib\site-packages\flask\app.py:1892]
Traceback (most recent call last):
  File "c:\users\lolip\appdata\local\programs\python\python36\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\lolip\appdata\local\programs\python\python36\lib\site-packages\flask\app.py", line 1953, in full_dispatch_request
    return self.finalize_request(rv)
  File "c:\users\lolip\appdata\local\programs\python\python36\lib\site-packages\flask\app.py", line 1968, in finalize_request
    response = self.make_response(rv)
  File "c:\users\lolip\appdata\local\programs\python\python36\lib\site-packages\flask\app.py", line 2112, in make_response
    rv = jsonify(rv)
  File "c:\users\lolip\appdata\local\programs\python\python36\lib\site-packages\flask\json\__init__.py", line 370, in jsonify
    dumps(data, indent=indent, separators=separators) + "\n",
  File "c:\users\lolip\appdata\local\programs\python\python36\lib\site-packages\flask\json\__init__.py", line 211, in dumps
    rv = _json.dumps(obj, **kwargs)
  File "c:\users\lolip\appdata\local\programs\python\python36\lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "c:\users\lolip\appdata\local\programs\python\python36\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "c:\users\lolip\appdata\local\programs\python\python36\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "c:\users\lolip\appdata\local\programs\python\python36\lib\site-packages\flask\json\__init__.py", line 100, in default
    return _json.JSONEncoder.default(self, o)
  File "c:\users\lolip\appdata\local\programs\python\python36\lib\json\encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'Run' is not JSON serializable
2021-05-18 12:42:46,623 ERROR: Exception on /api/5/run [POST] [in c:\users\lolip\appdata\local\programs\python\python36\lib\site-packages\flask\app.py:1892]
Traceback (most recent call last):
  File "c:\users\lolip\appdata\local\programs\python\python36\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\lolip\appdata\local\programs\python\python36\lib\site-packages\flask\app.py", line 1953, in full_dispatch_request
    return self.finalize_request(rv)
  File "c:\users\lolip\appdata\local\programs\python\python36\lib\site-packages\flask\app.py", line 1968, in finalize_request
    response = self.make_response(rv)
  File "c:\users\lolip\appdata\local\programs\python\python36\lib\site-packages\flask\app.py", line 2112, in make_response
    rv = jsonify(rv)
  File "c:\users\lolip\appdata\local\programs\python\python36\lib\site-packages\flask\json\__init__.py", line 370, in jsonify
    dumps(data, indent=indent, separators=separators) + "\n",
  File "c:\users\lolip\appdata\local\programs\python\python36\lib\site-packages\flask\json\__init__.py", line 211, in dumps
    rv = _json.dumps(obj, **kwargs)
  File "c:\users\lolip\appdata\local\programs\python\python36\lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "c:\users\lolip\appdata\local\programs\python\python36\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "c:\users\lolip\appdata\local\programs\python\python36\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "c:\users\lolip\appdata\local\programs\python\python36\lib\site-packages\flask\json\__init__.py", line 100, in default
    return _json.JSONEncoder.default(self, o)
  File "c:\users\lolip\appdata\local\programs\python\python36\lib\json\encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'Run' is not JSON serializable
2021-05-18 12:42:46,623 ERROR: Exception on /api/5/run [POST] [in c:\users\lolip\appdata\local\programs\python\python36\lib\site-packages\flask\app.py:1892]
Traceback (most recent call last):
  File "c:\users\lolip\appdata\local\programs\python\python36\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\lolip\appdata\local\programs\python\python36\lib\site-packages\flask\app.py", line 1953, in full_dispatch_request
    return self.finalize_request(rv)
  File "c:\users\lolip\appdata\local\programs\python\python36\lib\site-packages\flask\app.py", line 1968, in finalize_request
    response = self.make_response(rv)
  File "c:\users\lolip\appdata\local\programs\python\python36\lib\site-packages\flask\app.py", line 2112, in make_response
    rv = jsonify(rv)
  File "c:\users\lolip\appdata\local\programs\python\python36\lib\site-packages\flask\json\__init__.py", line 370, in jsonify
    dumps(data, indent=indent, separators=separators) + "\n",
  File "c:\users\lolip\appdata\local\programs\python\python36\lib\site-packages\flask\json\__init__.py", line 211, in dumps
    rv = _json.dumps(obj, **kwargs)
  File "c:\users\lolip\appdata\local\programs\python\python36\lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "c:\users\lolip\appdata\local\programs\python\python36\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "c:\users\lolip\appdata\local\programs\python\python36\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "c:\users\lolip\appdata\local\programs\python\python36\lib\site-packages\flask\json\__init__.py", line 100, in default
    return _json.JSONEncoder.default(self, o)
  File "c:\users\lolip\appdata\local\programs\python\python36\lib\json\encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'Run' is not JSON serializable
2021-05-18 12:43:06,491 INFO: uvo-reserves [in C:\Users\lolip\Desktop\Git projects\uvo-reserves-demo\app\__init__.py:80]
2021-05-18 12:43:06,491 INFO: uvo-reserves startup [in C:\Users\lolip\Desktop\Git projects\uvo-reserves-demo\app\__init__.py:101]
2021-05-18 12:43:06,491 INFO: uvo-reserves startup [in C:\Users\lolip\Desktop\Git projects\uvo-reserves-demo\app\__init__.py:101]
2021-05-18 12:43:12,798 INFO: uvo-reserves [in C:\Users\lolip\Desktop\Git projects\uvo-reserves-demo\app\__init__.py:80]
2021-05-18 12:43:12,798 INFO: uvo-reserves startup [in C:\Users\lolip\Desktop\Git projects\uvo-reserves-demo\app\__init__.py:101]
2021-05-18 12:43:12,798 INFO: uvo-reserves startup [in C:\Users\lolip\Desktop\Git projects\uvo-reserves-demo\app\__init__.py:101]
2021-05-18 12:44:24,076 INFO: uvo-reserves [in C:\Users\lolip\Desktop\Git projects\uvo-reserves-demo\app\__init__.py:80]
2021-05-18 12:44:24,077 INFO: uvo-reserves startup [in C:\Users\lolip\Desktop\Git projects\uvo-reserves-demo\app\__init__.py:101]
2021-05-18 12:44:24,077 INFO: uvo-reserves startup [in C:\Users\lolip\Desktop\Git projects\uvo-reserves-demo\app\__init__.py:101]
2021-05-18 12:44:28,149 ERROR: Exception on /api/5/run [POST] [in c:\users\lolip\appdata\local\programs\python\python36\lib\site-packages\flask\app.py:1892]
Traceback (most recent call last):
  File "c:\users\lolip\appdata\local\programs\python\python36\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\lolip\appdata\local\programs\python\python36\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\lolip\appdata\local\programs\python\python36\lib\site-packages\flask_cors\extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "c:\users\lolip\appdata\local\programs\python\python36\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\lolip\appdata\local\programs\python\python36\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\lolip\appdata\local\programs\python\python36\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\lolip\appdata\local\programs\python\python36\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\lolip\appdata\local\programs\python\python36\lib\site-packages\flask_jwt_extended\view_decorators.py", line 121, in decorator
    return fn(*args, **kwargs)
  File "C:\Users\lolip\Desktop\Git projects\uvo-reserves-demo\app\api\run.py", line 45, in create_run
    'name': run.name
AttributeError: 'Run' object has no attribute 'name'
2021-05-18 12:47:36,650 INFO: uvo-reserves [in C:\Users\lolip\Desktop\Git projects\uvo-reserves-demo\app\__init__.py:80]
2021-05-18 12:47:36,650 INFO: uvo-reserves startup [in C:\Users\lolip\Desktop\Git projects\uvo-reserves-demo\app\__init__.py:101]
2021-05-18 12:47:36,650 INFO: uvo-reserves startup [in C:\Users\lolip\Desktop\Git projects\uvo-reserves-demo\app\__init__.py:101]
2021-05-18 13:02:56,673 INFO: uvo-reserves [in C:\Users\lolip\Desktop\Git projects\uvo-reserves-demo\app\__init__.py:80]
2021-05-18 13:02:56,674 INFO: uvo-reserves startup [in C:\Users\lolip\Desktop\Git projects\uvo-reserves-demo\app\__init__.py:101]
2021-05-18 13:02:56,674 INFO: uvo-reserves startup [in C:\Users\lolip\Desktop\Git projects\uvo-reserves-demo\app\__init__.py:101]
